// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: bor/bor.proto

package bor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BorApiClient is the client API for BorApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BorApiClient interface {
	GetRootHash(ctx context.Context, in *GetRootHashRequest, opts ...grpc.CallOption) (*GetRootHashResponse, error)
	GetVoteOnHash(ctx context.Context, in *GetVoteOnHashRequest, opts ...grpc.CallOption) (*GetVoteOnHashResponse, error)
	GetHeaderByNumber(ctx context.Context, in *GetHeaderByNumberRequest, opts ...grpc.CallOption) (*GetHeaderByNumberResponse, error)
	GetBlockByNumber(ctx context.Context, in *GetBlockByNumberRequest, opts ...grpc.CallOption) (*GetBlockByNumberResponse, error)
	GetTransactionReceipt(ctx context.Context, in *ReceiptRequest, opts ...grpc.CallOption) (*ReceiptResponse, error)
	GetBorBlockReceipt(ctx context.Context, in *ReceiptRequest, opts ...grpc.CallOption) (*ReceiptResponse, error)
}

type borApiClient struct {
	cc grpc.ClientConnInterface
}

func NewBorApiClient(cc grpc.ClientConnInterface) BorApiClient {
	return &borApiClient{cc}
}

func (c *borApiClient) GetRootHash(ctx context.Context, in *GetRootHashRequest, opts ...grpc.CallOption) (*GetRootHashResponse, error) {
	out := new(GetRootHashResponse)
	err := c.cc.Invoke(ctx, "/bor.BorApi/GetRootHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borApiClient) GetVoteOnHash(ctx context.Context, in *GetVoteOnHashRequest, opts ...grpc.CallOption) (*GetVoteOnHashResponse, error) {
	out := new(GetVoteOnHashResponse)
	err := c.cc.Invoke(ctx, "/bor.BorApi/GetVoteOnHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borApiClient) GetHeaderByNumber(ctx context.Context, in *GetHeaderByNumberRequest, opts ...grpc.CallOption) (*GetHeaderByNumberResponse, error) {
	out := new(GetHeaderByNumberResponse)
	err := c.cc.Invoke(ctx, "/bor.BorApi/GetHeaderByNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borApiClient) GetBlockByNumber(ctx context.Context, in *GetBlockByNumberRequest, opts ...grpc.CallOption) (*GetBlockByNumberResponse, error) {
	out := new(GetBlockByNumberResponse)
	err := c.cc.Invoke(ctx, "/bor.BorApi/GetBlockByNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borApiClient) GetTransactionReceipt(ctx context.Context, in *ReceiptRequest, opts ...grpc.CallOption) (*ReceiptResponse, error) {
	out := new(ReceiptResponse)
	err := c.cc.Invoke(ctx, "/bor.BorApi/GetTransactionReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borApiClient) GetBorBlockReceipt(ctx context.Context, in *ReceiptRequest, opts ...grpc.CallOption) (*ReceiptResponse, error) {
	out := new(ReceiptResponse)
	err := c.cc.Invoke(ctx, "/bor.BorApi/GetBorBlockReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BorApiServer is the server API for BorApi service.
// All implementations must embed UnimplementedBorApiServer
// for forward compatibility
type BorApiServer interface {
	GetRootHash(context.Context, *GetRootHashRequest) (*GetRootHashResponse, error)
	GetVoteOnHash(context.Context, *GetVoteOnHashRequest) (*GetVoteOnHashResponse, error)
	GetHeaderByNumber(context.Context, *GetHeaderByNumberRequest) (*GetHeaderByNumberResponse, error)
	GetBlockByNumber(context.Context, *GetBlockByNumberRequest) (*GetBlockByNumberResponse, error)
	GetTransactionReceipt(context.Context, *ReceiptRequest) (*ReceiptResponse, error)
	GetBorBlockReceipt(context.Context, *ReceiptRequest) (*ReceiptResponse, error)
	mustEmbedUnimplementedBorApiServer()
}

// UnimplementedBorApiServer must be embedded to have forward compatible implementations.
type UnimplementedBorApiServer struct {
}

func (UnimplementedBorApiServer) GetRootHash(context.Context, *GetRootHashRequest) (*GetRootHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRootHash not implemented")
}
func (UnimplementedBorApiServer) GetVoteOnHash(context.Context, *GetVoteOnHashRequest) (*GetVoteOnHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoteOnHash not implemented")
}
func (UnimplementedBorApiServer) GetHeaderByNumber(context.Context, *GetHeaderByNumberRequest) (*GetHeaderByNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHeaderByNumber not implemented")
}
func (UnimplementedBorApiServer) GetBlockByNumber(context.Context, *GetBlockByNumberRequest) (*GetBlockByNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByNumber not implemented")
}
func (UnimplementedBorApiServer) GetTransactionReceipt(context.Context, *ReceiptRequest) (*ReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionReceipt not implemented")
}
func (UnimplementedBorApiServer) GetBorBlockReceipt(context.Context, *ReceiptRequest) (*ReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBorBlockReceipt not implemented")
}
func (UnimplementedBorApiServer) mustEmbedUnimplementedBorApiServer() {}

// UnsafeBorApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BorApiServer will
// result in compilation errors.
type UnsafeBorApiServer interface {
	mustEmbedUnimplementedBorApiServer()
}

func RegisterBorApiServer(s grpc.ServiceRegistrar, srv BorApiServer) {
	s.RegisterService(&BorApi_ServiceDesc, srv)
}

func _BorApi_GetRootHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorApiServer).GetRootHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bor.BorApi/GetRootHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorApiServer).GetRootHash(ctx, req.(*GetRootHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorApi_GetVoteOnHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoteOnHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorApiServer).GetVoteOnHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bor.BorApi/GetVoteOnHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorApiServer).GetVoteOnHash(ctx, req.(*GetVoteOnHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorApi_GetHeaderByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeaderByNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorApiServer).GetHeaderByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bor.BorApi/GetHeaderByNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorApiServer).GetHeaderByNumber(ctx, req.(*GetHeaderByNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorApi_GetBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorApiServer).GetBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bor.BorApi/GetBlockByNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorApiServer).GetBlockByNumber(ctx, req.(*GetBlockByNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorApi_GetTransactionReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorApiServer).GetTransactionReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bor.BorApi/GetTransactionReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorApiServer).GetTransactionReceipt(ctx, req.(*ReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorApi_GetBorBlockReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorApiServer).GetBorBlockReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bor.BorApi/GetBorBlockReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorApiServer).GetBorBlockReceipt(ctx, req.(*ReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BorApi_ServiceDesc is the grpc.ServiceDesc for BorApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BorApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bor.BorApi",
	HandlerType: (*BorApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRootHash",
			Handler:    _BorApi_GetRootHash_Handler,
		},
		{
			MethodName: "GetVoteOnHash",
			Handler:    _BorApi_GetVoteOnHash_Handler,
		},
		{
			MethodName: "GetHeaderByNumber",
			Handler:    _BorApi_GetHeaderByNumber_Handler,
		},
		{
			MethodName: "GetBlockByNumber",
			Handler:    _BorApi_GetBlockByNumber_Handler,
		},
		{
			MethodName: "GetTransactionReceipt",
			Handler:    _BorApi_GetTransactionReceipt_Handler,
		},
		{
			MethodName: "GetBorBlockReceipt",
			Handler:    _BorApi_GetBorBlockReceipt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bor/bor.proto",
}
